### ISSUE TITLE
4.0.0 Roadmap

### ISSUE THREAD

**Issue by SerafimArts** [phplrt/phplrt#15]
## Add (actualize) PHP 8.1 support
- Contracts (public interfaces)
  - [x] ast-contracts
  - [x] buffer-contracts
  - [x] grammar-contracts
  - [x] lexer-contracts
  - [x] parser-contracts
  - [x] position-contracts
  - [x] source-contracts
- Libraries
  - [x] buffer
  - [ ] compiler
  - [x] exception
  - [x] grammar
  - [x] lexer
  - [ ] parser
  - [x] position
  - [x] source
  - [ ] visitor
- Meta
  - [x] contracts
  - [x] runtime
## Refactoring
- New packages
  - [ ] Multistate lexer (split from lexer 3.x)
  - [ ] Builder (code mangling)
  - [ ] Source maps (?)
- Rewritten packages
  - [ ] exception
    - [x] Remove general runtime exception
    - [ ] Add features to highlight exceptions
- Deprecated packages
  - [ ] grammar + grammar-contracts (merge with parser)
  - [ ] ast-contracts (replace to `Traversable` interface)
## Other
- Vimeo Psalm `level=1` compatibility
  - [x] ast-contracts
  - [x] buffer-contracts
  - [x] grammar-contracts
  - [x] lexer-contracts
  - [x] parser-contracts
  - [x] position-contracts
  - [x] source-contracts
  - [x] buffer
  - [ ] compiler
  - [x] exception
  - [x] grammar
  - [x] lexer
  - [ ] parser
  - [x] position
  - [ ] source
  - [ ] visitor
